version: "3.8"

services:
  mysql:
    image: mysql:8
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
    volumes:
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql

  backend:
    build:
      context: ./base-back
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/${DB_NAME}
      SPRING_DATASOURCE_USERNAME: ${DB_USER}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
      SPRING_PROFILES_ACTIVE: prod
    depends_on:
      - mysql

  nginx:
    build:
      context: ./base-front
      args:
        CONFIG: production
        BASE_HREF: /easygroup/
    ports:
      - "4200:80"
    volumes:
      - ./base-front/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend
