version: "3.8"

services:
  mysql:
    image: mysql:8
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
    volumes:
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql

  backend:
    build:
      context: ./base-back
    ports:
      - "8081:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/${DB_NAME}
      SPRING_DATASOURCE_USERNAME: ${DB_USER}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
      SPRING_PROFILES_ACTIVE: staging
    depends_on:
      - mysql

  frontend:
    build:
      context: ./base-front
      args:
        CONFIG: staging
    environment:
      - NODE_ENV=staging
      - BASE_HREF=/easygroup-staging/
    depends_on:
      - backend
    # Ce conteneur ne sert pas directement le front, il génère les fichiers statiques

  nginx:
    image: nginx:alpine
    ports:
      - "4201:80"
    volumes:
      - ./base-front/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./base-front/dist/easy-group/browser:/usr/share/nginx/html
      - ./base-front/nginx/wait-for-frontend.sh:/wait-for-frontend.sh
    depends_on:
      - frontend
      - backend
  command: ["/bin/sh", "/wait-for-frontend.sh"]

