version: "3.8"

services:
  mysql:
    image: mysql:8
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
    volumes:
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
    container_name: mysql_prod

  backend:
    build:
      context: ./base-back
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/${DB_NAME}
      SPRING_DATASOURCE_USERNAME: ${DB_USER}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
      SPRING_PROFILES_ACTIVE: prod
    depends_on:
      - mysql
    container_name: backend_prod

  frontend:
    build:
      context: ./base-front
      target: build
      args:
        CONFIG: production
    ports:
      - "${FRONT_PORT}:${CONTAINER_FRONT_PORT}"  # 4200:80 via .env.prod
    environment:
      - NODE_ENV=production
    depends_on:
      - backend
    container_name: frontend_prod
