name: Deploy to Production

on:
  workflow_dispatch:  # Déclenchement manuel dans GitHub Actions

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Tailscale (OAuth)
        uses: tailscale/github-action@v3
        with:
          oauth-client-id: ${{ secrets.TS_OAUTH_CLIENT_ID }}
          oauth-secret: ${{ secrets.TS_OAUTH_SECRET }}
          tags: tag:ci

      - name: Deploy to prod via Tailscale SSH
        run: |
          ssh -o StrictHostKeyChecking=no pi@raspberrypi.tail06bcb8.ts.net "
            cd easy-group &&
            git pull origin main &&
            docker compose --env-file .env.prod -f docker-compose.prod.yml up --build -d
          "
