name: Deploy to Production

on:
  workflow_dispatch:  # bouton manuel dans GitHub Actions

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to prod (SSH)
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.PROD_HOST }}
          username: ${{ secrets.PROD_USER }}
          key: ${{ secrets.PROD_SSH_KEY }}
          script: |
            cd easy-group
            git pull origin main
            docker-compose --env-file .env.prod -f docker-compose.prod.yml up --build -d
